version: '2'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - ./configs/conf.d/:/etc/nginx/conf.d/
      - ./certs/:/etc/ssl/private/
      - /mnt/extensions/:/serve/app/exts/

  filewatcher:
    image: elran777/vscode-ex-server_filewatcher
    depends_on:
      - server
    volumes:
      - /mnt/extensions/:/app/exts/

  server:
    image: elran777/vscode-ex-server_server
    ports:
      - 8443:8443
    volumes:
      - /mnt/extensions/:/app/exts/
